### ISSUE TITLE
maildrop.cc

### ISSUE THREAD

**Issue by HackG** [m242/maildrop#21]
Is the site down? I have tried to access the site several times lately with no luck

http://www.downforeveryoneorjustme.com/http://maildrop.cc/

**Comment by Ashtor** [comment]
It would be awesome to get an answer on this question as soon as you have got the message. here are my question:
1. When I send a email to any email that ends with @maildrop.cc ,no messages comes into "inbox" on http://maildrop.cc at all.. Why not? is it because the site is used only for preventing spam? because no messages at all comes to "inbox" there at all
2. Does the site works at all? because Nothing comes into inbox on the site

**Comment by Ashtor** [comment]
Hi.
Can you please answer the 4 questions I posted on april 12th 2016? I dont know other places to ask them pluas there is no other wayto contct you

**Comment by dazoe** [comment]
I too would like answers to question 3 because I can't even send email to the maildrop.cc's contact us email. Please stop using the SORBS black list they are no good.
